
- name: Install Docker and Docker Compose
  hosts: servers
  become: true
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ DOCKER_IMAGE }}"
        source: pull

    - name: Create directory of Dockerfile
      file:
        path: /opt/app/manage-frontend/.docker-compose
        state: directory
        recurse: yes

   
    - name: Copy file from GitHub Actions to target server
      ansible.builtin.copy:
        src: "{{DOCKERFILE_SRC}}"
        dest: /opt/app/manage-frontend/.docker-compose
        mode: "0644"
    
    - name: Run Docker Compose
      docker_compose:
        project_src: /opt/app/manage-frontend/.docker-compose
        state: present
        build: no
        pull: yes
      environment:
        DOCKER_IMAGE: "{{ DOCKER_IMAGE }}"
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
